libtrap: add error message when UniRec negotiation fails
When UniRec specifiers are compared, the negotiation can result in
failure: "error: output and input interfaces data formats or data
specifiers mismatch"
without further information.

This patch adds an error message that prints a required field that was not found
in the senders specifier.

Example of python module:

```
1328:(master) libtrap$ cat negotest.py
import pytrap
p = pytrap.TrapCtx()
p.init(["-i", "u:abc"], 1)
p.setRequiredFmt(0, pytrap.FMT_UNIREC, "int64 NONEXISTING")
p.recv()
1329:(master) libtrap$ ./negotest.py
ERROR: TRAP Negotiation failed: required field `int64 NONEXISTING` not sent by sender.
Received specifier: ipaddr DST_IP,ipaddr SRC_IP,uint64 BYTES,uint64 LINK_BIT_FIELD,time TIME_FIRST,time TIME_LAST,macaddr DST_MAC,macaddr SRC_MAC,uint32 PACKETS,uint16 DST_PORT,uint16 SRC_PORT,uint8 DIR_BIT_FIELD,uint8 PROTOCOL,uint8 TCP_FLAGS,uint8 TOS,uint8 TTL
Traceback (most recent call last):
  File "./negotest.py", line 6, in <module>
    p.recv()
pytrap.FormatMismatch: Format mismatch, incompatible data format of sender and receiver.
```